from typing import Optional
from pydantic import BaseModel, Field

class IndicadoresProgramaBase(BaseModel):
    numero_ficha: int = Field(..., gt=0)  # NUEVO: número de ficha único
    cod_programa: int = Field(..., gt=0)  # Parte de PK compuesta
    version: str = Field(..., min_length=1, max_length=4)  # NUEVO: versión del programa
    
    # Campos de indicadores (todos opcionales)
    indig_despl_viol_apr_tot: Optional[int] = Field(None, ge=0)
    indig_despl_viol_cab_fam_apr_tot: Optional[int] = Field(None, ge=0)
    afro_despl_viol_apr_tot: Optional[int] = Field(None, ge=0)
    afro_despl_viol_cab_fam_apr_tot: Optional[int] = Field(None, ge=0)
    despl_viol_apr_tot: Optional[int] = Field(None, ge=0)
    despl_viol_cab_fam_apr_tot: Optional[int] = Field(None, ge=0)
    despl_disc_apr_tot: Optional[int] = Field(None, ge=0)
    despojo_apr_tot: Optional[int] = Field(None, ge=0)
    act_grup_arm_apr_tot: Optional[int] = Field(None, ge=0)
    amenaza_apr_tot: Optional[int] = Field(None, ge=0)
    del_sex_apr_tot: Optional[int] = Field(None, ge=0)
    desap_forz_apr_tot: Optional[int] = Field(None, ge=0)
    homi_masac_apr_tot: Optional[int] = Field(None, ge=0)
    minas_exp_apr_tot: Optional[int] = Field(None, ge=0)
    secuestro_apr_tot: Optional[int] = Field(None, ge=0)
    tortura_apr_tot: Optional[int] = Field(None, ge=0)
    uso_men_grup_arm_apr_tot: Optional[int] = Field(None, ge=0)
    herido_apr_tot: Optional[int] = Field(None, ge=0)
    reclut_forz_apr_tot: Optional[int] = Field(None, ge=0)
    negro_apr_tot: Optional[int] = Field(None, ge=0)
    afro_apr_tot: Optional[int] = Field(None, ge=0)
    palenq_apr_tot: Optional[int] = Field(None, ge=0)
    raizal_apr_tot: Optional[int] = Field(None, ge=0)
    discap_apr_tot: Optional[int] = Field(None, ge=0)
    discap_aud_apr_tot: Optional[int] = Field(None, ge=0)
    discap_vis_apr_tot: Optional[int] = Field(None, ge=0)
    discap_fis_apr_tot: Optional[int] = Field(None, ge=0)
    discap_int_apr_tot: Optional[int] = Field(None, ge=0)
    discap_psico_apr_tot: Optional[int] = Field(None, ge=0)
    discap_mult_apr_tot: Optional[int] = Field(None, ge=0)
    sordoceg_apr_tot: Optional[int] = Field(None, ge=0)
    despl_fen_nat_apr_tot: Optional[int] = Field(None, ge=0)
    despl_fen_nat_cab_fam_apr_tot: Optional[int] = Field(None, ge=0)
    adol_conf_ley_apr_tot: Optional[int] = Field(None, ge=0)
    adol_trab_apr_tot: Optional[int] = Field(None, ge=0)
    indig_apr_tot: Optional[int] = Field(None, ge=0)
    inpec_apr_tot: Optional[int] = Field(None, ge=0)
    jov_vuln_apr_tot: Optional[int] = Field(None, ge=0)
    muj_cabfam_apr_tot: Optional[int] = Field(None, ge=0)
    proc_reint_apr_tot: Optional[int] = Field(None, ge=0)
    ado_desv_gr_arm_tot: Optional[int] = Field(None, ge=0)
    rem_pal_tot: Optional[int] = Field(None, ge=0)
    sob_min_ant_tot: Optional[int] = Field(None, ge=0)
    sold_camp_tot: Optional[int] = Field(None, ge=0)
    terc_edad_tot: Optional[int] = Field(None, ge=0)
    rom_tot: Optional[int] = Field(None, ge=0)
    camp_tot: Optional[int] = Field(None, ge=0)
    ning_tot: Optional[int] = Field(None, ge=0)
    artes_tot: Optional[int] = Field(None, ge=0)
    empr_tot: Optional[int] = Field(None, ge=0)
    mic_emp_tot: Optional[int] = Field(None, ge=0)
    rem_cie_tot: Optional[int] = Field(None, ge=0)
    gran_total: Optional[int] = Field(None, ge=0)


class CrearIndicadoresPrograma(IndicadoresProgramaBase):
    pass


class RetornoIndicadoresPrograma(IndicadoresProgramaBase):
    pass


class EditarIndicadoresPrograma(BaseModel):
    # No se pueden editar numero_ficha, cod_programa ni version (son parte de PK/FK)
    # Solo se pueden editar los campos de indicadores
    indig_despl_viol_apr_tot: Optional[int] = Field(None, ge=0)
    indig_despl_viol_cab_fam_apr_tot: Optional[int] = Field(None, ge=0)
    afro_despl_viol_apr_tot: Optional[int] = Field(None, ge=0)
    afro_despl_viol_cab_fam_apr_tot: Optional[int] = Field(None, ge=0)
    despl_viol_apr_tot: Optional[int] = Field(None, ge=0)
    despl_viol_cab_fam_apr_tot: Optional[int] = Field(None, ge=0)
    despl_disc_apr_tot: Optional[int] = Field(None, ge=0)
    despojo_apr_tot: Optional[int] = Field(None, ge=0)
    act_grup_arm_apr_tot: Optional[int] = Field(None, ge=0)
    amenaza_apr_tot: Optional[int] = Field(None, ge=0)
    del_sex_apr_tot: Optional[int] = Field(None, ge=0)
    desap_forz_apr_tot: Optional[int] = Field(None, ge=0)
    homi_masac_apr_tot: Optional[int] = Field(None, ge=0)
    minas_exp_apr_tot: Optional[int] = Field(None, ge=0)
    secuestro_apr_tot: Optional[int] = Field(None, ge=0)
    tortura_apr_tot: Optional[int] = Field(None, ge=0)
    uso_men_grup_arm_apr_tot: Optional[int] = Field(None, ge=0)
    herido_apr_tot: Optional[int] = Field(None, ge=0)
    reclut_forz_apr_tot: Optional[int] = Field(None, ge=0)
    negro_apr_tot: Optional[int] = Field(None, ge=0)
    afro_apr_tot: Optional[int] = Field(None, ge=0)
    palenq_apr_tot: Optional[int] = Field(None, ge=0)
    raizal_apr_tot: Optional[int] = Field(None, ge=0)
    discap_apr_tot: Optional[int] = Field(None, ge=0)
    discap_aud_apr_tot: Optional[int] = Field(None, ge=0)
    discap_vis_apr_tot: Optional[int] = Field(None, ge=0)
    discap_fis_apr_tot: Optional[int] = Field(None, ge=0)
    discap_int_apr_tot: Optional[int] = Field(None, ge=0)
    discap_psico_apr_tot: Optional[int] = Field(None, ge=0)
    discap_mult_apr_tot: Optional[int] = Field(None, ge=0)
    sordoceg_apr_tot: Optional[int] = Field(None, ge=0)
    despl_fen_nat_apr_tot: Optional[int] = Field(None, ge=0)
    despl_fen_nat_cab_fam_apr_tot: Optional[int] = Field(None, ge=0)
    adol_conf_ley_apr_tot: Optional[int] = Field(None, ge=0)
    adol_trab_apr_tot: Optional[int] = Field(None, ge=0)
    indig_apr_tot: Optional[int] = Field(None, ge=0)
    inpec_apr_tot: Optional[int] = Field(None, ge=0)
    jov_vuln_apr_tot: Optional[int] = Field(None, ge=0)
    muj_cabfam_apr_tot: Optional[int] = Field(None, ge=0)
    proc_reint_apr_tot: Optional[int] = Field(None, ge=0)
    ado_desv_gr_arm_tot: Optional[int] = Field(None, ge=0)
    rem_pal_tot: Optional[int] = Field(None, ge=0)
    sob_min_ant_tot: Optional[int] = Field(None, ge=0)
    sold_camp_tot: Optional[int] = Field(None, ge=0)
    terc_edad_tot: Optional[int] = Field(None, ge=0)
    rom_tot: Optional[int] = Field(None, ge=0)
    camp_tot: Optional[int] = Field(None, ge=0)
    ning_tot: Optional[int] = Field(None, ge=0)
    artes_tot: Optional[int] = Field(None, ge=0)
    empr_tot: Optional[int] = Field(None, ge=0)
    mic_emp_tot: Optional[int] = Field(None, ge=0)
    rem_cie_tot: Optional[int] = Field(None, ge=0)
    gran_total: Optional[int] = Field(None, ge=0)